---
- hosts: tag_Name_Backend
  vars:
    group_name: devuser
    user_name: devuser
    repo_user: <your_username>
    repo_pass: <your_pass>
    src_dir_name: backend
    project_path: "/home/{{ user_name }}/{{ src_dir_name }}/{{ src_dir_name }}"
    virtualenv_path: "/home/{{ user_name }}/{{ src_dir_name }}/env"
  tasks:
  - name: clone repositories
    git:
      repo: "https://{{ repo_user }}:{{ repo_pass }}@bitbucket.org/Arix_J/{{ src_dir_name }}.git"
      dest: "{{ project_path }}"

  - name: Create a directory if it does not exist
    file:
      path: "/home/{{ user_name }}/{{ src_dir_name }}"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ group_name }}"
      mode: 0755
      recurse: yes

  - name: Install virtualenv
    pip:
      name: virtualenv
      version: 15.1.0
           
  - name: Install packages required by the Django app inside virtualenv
    pip:
      virtualenv: "{{ virtualenv_path }}"
      requirements: "{{ project_path }}/requirements.txt"

  - name: Run Django database migrations
    django_manage:
      command: migrate
      app_path: "{{ project_path }}"
      virtualenv: "{{ virtualenv_path }}"

  - name: Collect Django static files
    django_manage:
      command: collectstatic
      app_path: "{{ project_path }}"
      virtualenv: "{{ virtualenv_path }}"
