image: cytopia/ansible

pipelines:
  branches:
    # deploy only when pushing to the master branch
    master:
      - step:
          name: Test
          script:
            - echo "Hello From BitBucket!"      
      - step:
          name: Deployment
          trigger: manual
          caches:
            # cache the installation
            - pip
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - pip install ansible boto3
            - cd revving
            - chmod 0400 .secrets/key.pem
            - ansible all -m date
            - ansible-playbook test.yml
